### ISSUE TITLE
请问这个模型中的action_dict.pkl 以及prediction.pkl怎么生成的

### ISSUE THREAD

**Issue by Duke-good** [hs1ang-hsu/BLAPose#1]
请问自己的训练模型如何生成这个action_dict.pkl 有和prediction.pkl文件

**Comment by hs1ang-hsu** [comment]
We generated `action_dict.pkl` and `prediction.pkl` by evaluating with other models. Take VideoPose3D as an example, we added a few lines to [run.py](https://github.com/facebookresearch/VideoPose3D/blob/main/run.py).

At line [699](https://github.com/facebookresearch/VideoPose3D/blob/1afb1ca0f1237776518469876342fc8669d3f6a9/run.py#L699), we collected the `predicted_3d_pos` by
```
predicted_3d_pos = predicted_3d_pos.cpu().numpy().reshape(-1, inputs_3d.shape[-2], inputs_3d.shape[-1]) 
output_prediction.append(predicted_3d_pos) 
```

After the evaluation is complete, we save `output_prediction` and `all_actions`, which is the evaluating order of subjects. At line [857](https://github.com/facebookresearch/VideoPose3D/blob/1afb1ca0f1237776518469876342fc8669d3f6a9/run.py#L857), we added
```
run_evaluation(all_actions, action_filter) 
import pickle 
pickle.dump(output_prediction, open('prediction.pkl', 'wb')) 
pickle.dump(all_actions, open('action_dict.pkl', 'wb')) 
```

**Comment by Duke-good** [comment]
可以分享一下在STCformer中如何生成action_dict.pkl和prediction.pkl吗？谢谢大佬！

**Comment by hs1ang-hsu** [comment]
We add a few lines in [run_stc.py](https://github.com/zhenhuat/STCFormer/blob/main/run_stc.py)

We used a dictionary to save the results:
```
output_dict = {'S9': {}, 'S11': {}}
```
Since they did not provide the model with refine net, we just collect `output_3D_single` at line [69](https://github.com/zhenhuat/STCFormer/blob/74f660147438f762e2c6748246298c818630ab3f/run_stc.py#L69).
```
output_save = output_3D_single.clone().cpu().tolist() 
for i in range(len(output_save)): 
    if action[i] not in output_dict[subject[i]]: 
        output_dict[subject[i]][action[i]] = [] 
    output_dict[subject[i]][action[i]] += output_save[i] 
```

Then after the for loop (at line [105](https://github.com/zhenhuat/STCFormer/blob/74f660147438f762e2c6748246298c818630ab3f/run_stc.py#L105)), we converted the dictionary to our format. I'm sorry for the unorganized code. It works great for me.
```
import pickle
acts = ['Directions', 'Discussion', 'Eating', 'Greeting', 'Phoning', 'Photo', 'Posing', 'Purchases', 'Sitting', 'SittingDown', 'Smoking', 'Waiting', 'WalkDog', 'Walking', 'WalkTogether']
output_prediction = []
all_actions = {}
for act in acts:
    all_actions[act] = []
    for sub in ['S9', 'S11']:
        for a in output_dict[sub].keys():
            if act == 'Sitting' and 'SittingDown' in a:
                continue
            if act in a:
                all_actions[act].append((sub, a))
                N = len(output_dict[sub][a])
                segment = int(N/4)
                for i in range(0, N, segment):
                    output_prediction.append(np.array(output_dict[sub][a][i:i+segment]))

pickle.dump(output_prediction, open('prediction.pkl', 'wb'))
pickle.dump(all_actions, open('action_dict.pkl', 'wb'))
```

**Comment by Duke-good** [comment]
感谢您的回答，我对您的这篇文章非常感兴趣，冒昧的问一下，对于调整后的模型，如何进行可视化，或者说输入一段视频如何能预测关键点。

**Comment by hs1ang-hsu** [comment]
Thank you for your interest in this work. We just added the instructions for visualization. Please refer to [Visualization](https://github.com/hs1ang-hsu/BLAPose?tab=readme-ov-file#visualization-inference-in-the-wild).

**Comment by Duke-good** [comment]
谢谢您的分享，请问您这个方法可以泛化到3DHP数据集上吗

**Comment by hs1ang-hsu** [comment]
Applying our method to other datasets is challenging. Our work focuses on adjusting bone lengths, but different MoCap datasets define joint positions differently—even within the same dataset, as seen in Human3.6M across different subjects. For instance, the "head" joint in 3DHP corresponds to the top of the head, whereas in Human3.6M, it is closer to the midpoint between the eyes.

Another challenge lies in generating synthetic bone lengths. In our approach, we first create 3D human meshes and then transform them into joint positions formatted for Human3.6M. However, existing works do not provide a transformation from 3D meshes to 3DHP joint positions. To apply our method to 3DHP, the following steps would be required:

- Identify the regression matrix to transform 3D human meshes into joint positions in the 3DHP format
- Generate 3D meshes using SMPL and convert them into bone lengths
- Train the bone length model using these synthetic bone lengths

**Comment by Duke-good** [comment]
谢谢您的分享，请问您使用的mmcv和mmpose版本分别是多少呢？为什么我一直会出现ImportError: cannot import name 'MMPoseInferencer' from 'mmpose.apis' (D:\Anaconda\envs\pose\lib\site-packages\mmpose\apis\__init__.py)这个错误！

**Comment by hs1ang-hsu** [comment]
Thank you for letting me know what is missing. The versions of these packages are listed below:
mmcv=2.0.1
mmdet=3.1.0
mmengine=0.8.4
mmpose=1.1.0
mmpretrain=1.0.1

**Comment by Duke-good** [comment]
您好，请问在微调的时候如果用其他模型进行微调

**Comment by Duke-good** [comment]
您好，请问在进行微调的时候怎么用其他模型进行微调

**Comment by hs1ang-hsu** [comment]
You should modify the following files:
- `utils/model_conv.py`: this is the model for 2D-to-3D lifting. Currently, it is `model.py` in [VideoPose3D](https://github.com/facebookresearch/VideoPose3D/blob/main/common/model.py). You can modify it to other models.
- `utils/model_mix.py`: this model is the fine-tuned model. You should modify how it initializes model_conv.
- `main.py`: in the function `load_model`, you should modify how it initializes model_mix.

Actually, we find that the fine-tuned model does not work well with other models. We suggest that you should use the adjustment directly by integrating the model you want to use with our `inference.py`.


As for why fine-tuned models fail to work well, the reason is as follow:

*Our goal is to enhance bone length prediction in existing lifting models. The success of this improvement relies on the models' ability to accurately predict bone directions. However, adjusting bone lengths often neglects 2D alignment. To address this, we introduced a fine-tuning process aimed at refining bone direction using bone length cues. Unfortunately, we observed that several lifting models suffer from flipping ambiguity [1], which bone length cues alone cannot resolve. As a result, the fine-tuning process did not improve some of the lifting models. We believe that if flipping ambiguity can be mitigated, bone length cues could be more effective in enhancing these models. We have set this as a focus for future work.*
[1] flipping ambiguity: finite possible 3D poses arise by flipping each bone forwards or backwards

**Comment by Duke-good** [comment]
好的非常感谢您的回答，我在进行可视化的时候遇到了一个问题，不知道是什么原因。我是直接使用自己模型的demo生成的3D预测文件进行可视化，不知道是不是因为我这个生成的文件有问题。
Traceback (most recent call last):
  File "inference.py", line 115, in <module>
    inference(args)
  File "inference.py", line 77, in inference
    re_kpts = detect2d(video, save_video=False)
  File "/root/bla/vis_utils/detector.py", line 60, in detect2d
    ret_bbox = people_track[-1, :-1]
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by hs1ang-hsu** [comment]
這是因為我使用的 2D keypoints detector 沒有在畫面中偵測到人物，這個 detector 會先使用 yolox 找出人物位置，再使用 ViTPose 從影像中算出 2D keypoints 的位置。你遇到的這個問題是 yolox 沒有找到人物，可能可以嘗試修改 `detector.py` 裡面 `pose_model` 所使用的 `det_model`，或是改成使用新版 mmpose 所提供的 detector。

**Comment by Duke-good** [comment]
谢谢您的提示，我已经成功解决了这个问题，但是为什么我使用自己预测的关键点进行可视化就会出现错误，就是预测出来的和视频完全对不上

**Comment by hs1ang-hsu** [comment]
Please send me (r11944034@ntu.edu.tw) your materials, including the video and the predicted 3D poses. I will take a look when I am free.

**Comment by Duke-good** [comment]
好的谢谢您的耐心回复，已经发到您邮箱了

**Comment by Duke-good** [comment]
如何得到对于2D升3D模型进行骨长调整后的关键点坐标?

**Comment by hs1ang-hsu** [comment]
The [pred_pose_adjusted](https://github.com/hs1ang-hsu/BLAPose/blob/c9e95af21c238c023efe8286326970de59238085/inference.py#L95C9-L95C28) is what you want.

**Comment by Duke-good** [comment]
请问在训练bi-GRU时，为什么最好的epoch结果，在进行2D升3D调整时效果很差，应该取第几轮结果作为最好的结果

**Comment by hs1ang-hsu** [comment]
We found that our models converge after approximately five epochs, with the best results observed between 5 to 10 epochs. Consistent results were achieved across different random seeds and model parameters. However, we also noticed that performance gets worse after 20 epochs.
We believe this is related to noise in the 2D keypoints. Our synthetic data uses 2D keypoints projected from 3D poses, which are noise-free. In contrast, the 2D keypoints in the test set are predicted from videos and inherently noisy. As our bone length models become better at predicting bone lengths using noise-free data, their ability to handle noisy data diminishes.
